### ISSUE TITLE
Patron barcodes don't reliably print

### ISSUE THREAD

**Issue by lucasschneider** [lucasschneider/mpl-koha-patch-WE#1]
The HTML page opens silently in a new tab every time, but the script to add the barcode and execute printing doesn't always apply successfully.

**Comment by robert-byrne** [comment]
I might have found the problem. I noticed in your version 18.0.1 that you switched many of your chrome.<function-name> references to browser.<function-name>. However, with the printBarcode.js, you still have it as chrome.<function-name>. My assumption would be that Firefox would not have a parent "chrome" object, and since it is still chrome.<function-name>, My guess is that is where the error on the print barcode is occurring.

**Comment by lucasschneider** [comment]
For the time being, if you can click the button twice in quick succession and it should print--I'm still trying to figure out why all of the scripts seem to be running twice.

**Comment by lucasschneider** [comment]
This issue seems to have been resolved after SCLS upgraded to Firefox 54.*
